version: '3'
services:
  vue:
    build:
      context: ./knights-challenge
      dockerfile: Dockerfile.vue
    volumes:
      - ./knights-challenge:/app
      - /app/node_modules
    ports:
      - 8080:8080
    environment:
      - CHOKIDAR_USEPOLLING=true

  nestjs:
    build:
      context: ./knights-challenge-api
      dockerfile: Dockerfile.nestjs
    volumes:
      - ./knights-challenge-api:/app
      - /app/node_modules
    ports:
      - 3000:3000

  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017